# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::CONFIG; end
module ::CodeClimate::TestReporter; end
module ::RubyInstaller::Runtime; end
module Sorbet::Private::GemGeneratorTracepoint::TracepointSerializer; end
module Sorbet::Private::GemGeneratorTracepoint::Tracer; end
